// frontend/src/components/filesyncer/ConfigList.tsx
import { Button } from '@/components/ui/button'
import { PencilIcon, TrashIcon } from 'lucide-react'
import type { types } from '../../../wailsjs/go/models'

interface ConfigListProps {
  configs: types.SSHConfig[]
  selectedId: string | null
  onSelect: (id: string) => void
  onNew: () => void
  onEdit: (id: string) => void
  onDelete: (id: string) => void
}

export function ConfigList({
  configs,
  selectedId,
  onSelect,
  onNew,
  onEdit,
  onDelete,
}: ConfigListProps) {
  return (
    <div className="p-4 h-full flex flex-col bg-muted/50">
      <Button onClick={onNew} className="w-full mb-4">
        + New Configuration
      </Button>

      <ul className="space-y-1 overflow-y-auto text-left">
        {configs.map((config) => (
          <li
            key={config.id}
            onClick={() => onSelect(config.id)}
            className={`p-3 rounded-md cursor-pointer flex justify-between items-center transition-colors group ${
              selectedId === config.id
                ? 'bg-accent text-accent-foreground'
                : 'hover:bg-accent hover:text-accent-foreground'
            }`}
            onMouseEnter={() => console.log('Hover on:', config.id)} // 调试 hover
          >
            <div>
              <h3 className="font-semibold text-sm">{config.name}</h3>
              <p className="text-xs text-muted-foreground">
                {config.user}@{config.host}
              </p>
            </div>

            <div className="flex items-center opacity-0 group-hover:opacity-100 transition-opacity">
              {/* <div className="flex items-center opacity-100 transition-opacity"> */}
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={(e) => {
                  e.stopPropagation()
                  onEdit(config.id)
                }}
                title="Edit Configuration"
              >
                <PencilIcon className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 hover:bg-destructive/10 hover:text-destructive"
                onClick={(e) => {
                  e.stopPropagation()
                  onDelete(config.id)
                }}
                title="Delete Configuration"
              >
                <TrashIcon className="h-4 w-4" />
              </Button>
            </div>
          </li>
        ))}
      </ul>
    </div>
  )
}

// frontend/src/components/filesyncer/ConfigList.vue
<script setup>
import {PencilIcon,TrashIcon} from '@heroicons/vue/24/solid'; // 导入编辑图标

defineProps(['configs', 'selectedId']);
const emit = defineEmits(['select-config', 'configs-updated', 'new-config-request', 'edit-config', 'delete-config']);

function createNewConfig() {
  // 打开一个模态框来创建新配置
  emit('new-config-request');
}
</script>

<template>
  <div class="p-4 h-full flex flex-col">
    <button @click="createNewConfig"
            class="w-full bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 transition mb-4">
      + New Configuration
    </button>
    <ul class="space-y-2 overflow-y-auto text-left">
      <li
          v-for="config in configs"
          :key="config.id"
          @click="emit('select-config', config.id)"
          class="p-3 rounded-md cursor-pointer transition flex justify-between items-center"
          :class="[selectedId === config.id ? 'bg-indigo-100 dark:bg-indigo-900/50' : 'hover:bg-gray-200 dark:hover:bg-gray-700']"
      >
        <div>
          <h3 class="font-semibold text-sm">{{ config.name }}</h3>
          <p class="text-xs text-gray-500 dark:text-gray-400">{{ config.user }}@{{ config.host }}</p>
        </div>

        <div class="flex items-center space-x-1 flex-shrink-0">
          <button
              @click.stop="emit('edit-config', config.id)"
              class="p-1 text-gray-400 hover:text-gray-800 dark:hover:text-white rounded-full hover:bg-gray-300 dark:hover:bg-gray-600"
              title="Edit Configuration"
          >
            <PencilIcon class="h-4 w-4"/>
          </button>

          <button
              @click.stop="emit('delete-config', config.id)"
              class="p-1 text-gray-400 hover:text-red-500 rounded-full hover:bg-gray-300 dark:hover:bg-gray-600"
              title="Delete Configuration"
          >
            <TrashIcon class="h-4 w-4"/>
          </button>
        </div>
      </li>
    </ul>
  </div>
</template>
