// frontend/src/components/filesyncer/SyncPairsManager.tsx
import { useEffect, useState, useCallback } from 'react'
import {
  GetSyncPairs,
  SaveSyncPair,
  DeleteSyncPair,
  SelectDirectory,
  ShowConfirmDialog,
  ShowErrorDialog,
} from '../../../wailsjs/go/main/App'
import { types } from '../../../wailsjs/go/models'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Trash2 } from 'lucide-react'

interface SyncPairsManagerProps {
  config: types.SSHConfig
  isWatching: boolean
  onToggleWatcher: (id: string, isActive: boolean) => void
}

export function SyncPairsManager({
  config,
  isWatching,
  onToggleWatcher,
}: SyncPairsManagerProps) {
  const [syncPairs, setSyncPairs] = useState<types.SyncPair[]>([])
  const [showAddForm, setShowAddForm] = useState<boolean>(false)
  const [newPair, setNewPair] = useState({ localPath: '', remotePath: '' })

  const fetchSyncPairs = useCallback(async () => {
    if (!config.id) return
    try {
      const pairs = await GetSyncPairs(config.id)
      setSyncPairs(pairs)
    } catch (error) {
      await ShowErrorDialog(
        'Error',
        `Failed to fetch sync pairs: ${String(error)}`
      )
    } finally {
      console.log(`successed to fetch sync pairs for ${config.id}`)
    }
  }, [config.id])

  // 这个 effect 会在组件首次挂载时，以及 props.config.id 发生变化时
  // (即用户在左侧切换了配置) 自动重新获取同步对列表。
  useEffect(() => {
    void fetchSyncPairs()
  }, [fetchSyncPairs])

  const HandleBrowseLocal = async () => {
    const dirPath = await SelectDirectory('Select Local Directory')
    if (dirPath) {
      // 使用函数式更新获取上一个状态
      setNewPair((prev) => ({ ...prev, localPath: dirPath }))
    }
  }

  const handleSaveNewPair = async () => {
    if (!newPair.localPath || !newPair.remotePath) {
      return await ShowErrorDialog(
        'Error',
        'Local and Remote paths cannot be empty.'
      )
    }
    try {
      await SaveSyncPair({
        id: '',
        configId: config.id,
        localPath: newPair.localPath,
        remotePath: newPair.remotePath,
        syncDeletes: true, //默认开启删除同步
      })
      await fetchSyncPairs()
      setNewPair({ localPath: '', remotePath: '' })
      setShowAddForm(false)
    } catch (error) {
      await ShowErrorDialog(
        'Error',
        `Failed to save sync pair: ${String(error)}`
      )
    }
  }

  const handleDeletePair = async (pairId: string) => {
    const choice = await ShowConfirmDialog('Confirm Deletion', 'Are you sure?')
    if (choice !== 'Yes') return
    try {
      await DeleteSyncPair(pairId)
      await fetchSyncPairs() // 删除后刷新列表
    } catch (error) {
      await ShowErrorDialog(
        'Error',
        `Failed to delete sync pair: ${String(error)}`
      )
    }
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div className="space-y-1.5">
          <CardTitle>Sync Directories</CardTitle>
        </div>

        {/* 操作按钮组 */}
        <div className="flex items-center space-x-4">
          {/* 同步开关 */}
          <div className="flex items-center space-x-2">
            <Label
              htmlFor="sync-switch"
              className={`text-sm font-medium ${isWatching ? 'text-green-600' : 'text-muted-foreground'}`}
            >
              {isWatching ? 'Active' : 'Paused'}
            </Label>
            <Switch
              id="sync-switch"
              checked={isWatching}
              onCheckedChange={(checked) =>
                onToggleWatcher(config.id, checked)
              }
            />
          </div>
          <Button onClick={() => setShowAddForm(!showAddForm)} size="sm">
            + Add Pair
          </Button>
        </div>
      </CardHeader>

      <CardContent>
        {/* 添加新同步对的表单 (条件渲染) */}
        {showAddForm && (
          <div className="p-4 mb-4 bg-muted/50 rounded-lg space-y-4">
            <div>
              <Label className="text-xs">Local Path</Label>
              <div className="flex items-center">
                <Input
                  value={newPair.localPath}
                  readOnly
                  placeholder="Click Browse to select"
                />
                <Button
                  onClick={() => void HandleBrowseLocal()}
                  variant="outline"
                  className="ml-2"
                >
                  Browse
                </Button>
              </div>
            </div>

            <div>
              <Label className="text-xs">Remote Path</Label>
              <Input
                value={newPair.remotePath}
                onChange={(e) =>
                  setNewPair((prev) => ({
                    ...prev,
                    remotePath: e.target.value,
                  }))
                }
                placeholder="/var/www/my-project"
              />
            </div>
            <div className="flex justify-end space-x-2">
              <Button
                onClick={() => setShowAddForm(false)}
                variant="ghost"
                size="sm"
              >
                Cancel
              </Button>
              <Button onClick={() => void handleSaveNewPair()} size="sm">
                Save Pair
              </Button>
            </div>
          </div>
        )}

        {/* 已有同步对的列表 */}
        <div className="space-y-2">
          {syncPairs.length === 0 ? (
            <div className="text-center text-muted-foreground py-4">
              No sync pairs configured.
            </div>
          ) : (
            syncPairs.map((pair) => (
              <div
                key={pair.id}
                className="flex items-center justify-between p-3 bg-muted rounded-md"
              >
                <div className="font-mono text-sm">
                  <p className="text-sky-600 dark:text-sky-400">
                    {pair.localPath}
                  </p>
                  <p className="text-muted-foreground">➔ {pair.remotePath}</p>
                </div>
                <Button
                  onClick={() => void handleDeletePair(pair.id)}
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 hover:bg-destructive/10 hover:text-destructive"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            ))
          )}
        </div>
      </CardContent>
    </Card>
  )
}

// frontend/src/components/filesyncer/SyncPairsManager.vue
<script setup>
import { ref, onMounted, watch, reactive } from 'vue'
import { TrashIcon } from '@heroicons/vue/24/outline'
import {
  GetSyncPairs,
  SaveSyncPair,
  DeleteSyncPair,
  SelectDirectory,
  ShowConfirmDialog,
} from '../../../wailsjs/go/main/App'

const props = defineProps(['config', 'isWatching'])
const emit = defineEmits(['toggle-watcher'])

const syncPairs = ref([])
const showAddForm = ref(false)
const newPair = reactive({ localPath: '', remotePath: '' })

async function fetchSyncPairs() {
  if (!props.config?.id) return
  syncPairs.value = await GetSyncPairs(props.config.id)
}

onMounted(fetchSyncPairs)
watch(() => props.config.id, fetchSyncPairs)

async function handleBrowseLocalDirectory() {
  const dirPath = await SelectDirectory('Select Local Directory')
  if (dirPath) newPair.localPath = dirPath
}

async function handleSaveNewPair() {
  if (!newPair.localPath || !newPair.remotePath) return
  await SaveSyncPair({ configId: props.config.id, ...newPair, syncDeletes: true })
  await fetchSyncPairs()
  newPair.localPath = ''
  newPair.remotePath = ''
  showAddForm.value = false
}

async function handleDeletePair(pairId) {
  const choice = await ShowConfirmDialog(
    'Confirm Deletion',
    'Are you sure you want to delete this sync pair?'
  )
  if (choice !== 'Yes') return

  await DeleteSyncPair(pairId)
  await fetchSyncPairs()
}
</script>

<template>
  <div class="p-6 bg-white dark:bg-gray-800 rounded-lg shadow">
    <div class="flex justify-between items-center mb-4">
      <h2 class="text-xl font-bold">Sync Directories</h2>
      <div class="flex items-center space-x-4">
        <div class="flex items-center space-x-2">
          <span
            class="text-sm font-medium"
            :class="isWatching ? 'text-green-500' : 'text-gray-500'"
            >{{ isWatching ? 'Active' : 'Paused' }}</span
          >
          <button
            @click="emit('toggle-watcher', config.id, !isWatching)"
            class="relative inline-flex items-center h-6 rounded-full w-11 transition-colors"
            :class="isWatching ? 'bg-green-500' : 'bg-gray-300 dark:bg-gray-600'"
          >
            <span
              class="inline-block w-4 h-4 transform bg-white rounded-full transition-transform"
              :class="isWatching ? 'translate-x-6' : 'translate-x-1'"
            />
          </button>
        </div>
        <button
          @click="showAddForm = !showAddForm"
          class="bg-blue-600 text-white py-1 px-3 rounded-md hover:bg-blue-700 text-sm"
        >
          + Add Sync Pair
        </button>
      </div>
    </div>
    <div v-if="showAddForm" class="p-4 mb-4 bg-gray-50 dark:bg-gray-900/50 rounded-lg space-y-3">
      <div>
        <label class="block text-sm font-medium mb-1">Local Path</label>
        <div class="flex">
          <input
            v-model="newPair.localPath"
            type="text"
            readonly
            placeholder="Click Browse to select"
            class="w-full p-2 bg-gray-200 dark:bg-gray-700 rounded-l-md"
          />
          <button
            @click="handleBrowseLocalDirectory"
            class="px-3 py-2 bg-gray-300 dark:bg-gray-600 rounded-r-md text-sm"
          >
            Browse
          </button>
        </div>
      </div>
      <div>
        <label class="block text-sm font-medium mb-1">Remote Path</label>
        <input
          v-model="newPair.remotePath"
          type="text"
          placeholder="/var/www/my-project"
          class="w-full p-2 bg-gray-100 dark:bg-gray-700 rounded-md"
        />
      </div>
      <div class="flex justify-end space-x-2">
        <button
          @click="showAddForm = false"
          class="px-3 py-1 text-sm bg-gray-200 dark:bg-gray-600 rounded-md"
        >
          Cancel
        </button>
        <button
          @click="handleSaveNewPair"
          class="px-3 py-1 text-sm bg-green-600 text-white rounded-md"
        >
          Save Pair
        </button>
      </div>
    </div>
    <div class="space-y-2">
      <div v-if="syncPairs.length === 0" class="text-center text-gray-500 py-4">
        No sync pairs configured.
      </div>
      <div
        v-for="pair in syncPairs"
        :key="pair.id"
        class="flex items-center justify-between p-3 bg-gray-100 dark:bg-gray-700/50 rounded-md"
      >
        <div class="font-mono text-sm">
          <p class="text-blue-600 dark:text-blue-400">{{ pair.localPath }}</p>
          <p class="text-gray-500">➔ {{ pair.remotePath }}</p>
        </div>
        <button
          @click="handleDeletePair(pair.id)"
          class="p-1 text-gray-400 hover:text-red-500 rounded-full"
        >
          <TrashIcon class="h-5 w-5" />
        </button>
      </div>
    </div>
  </div>
</template>
